'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class database_firewall_rules
    Public Property id As Integer
    Public Property name As String
    Public Property start_ip_address As String
    Public Property end_ip_address As String
    Public Property create_date As Date
    Public Property modify_date As Date

End Class
Partial Public Class Drawback
    Public Property Drawback_Number As String
    Public Property status As String
    Public Property filed_date As Nullable(Of Date)

    Public Overridable Property Exports As ICollection(Of Export) = New HashSet(Of Export)

End Class
Partial Public Class Export
    Public Property Company As String
    Public Property Style As String
    Public Property SizeColor As String
    Public Property Export_Date As Date
    Public Property Freight_carrier As String
    Public Property Reference_number As String
    Public Property Export_Country As String
    Public Property Import_Date As Date
    Public Property Units As Nullable(Of Integer)
    Public Property Duty As Nullable(Of Decimal)
    Public Property Drawback_Number As String
    Public Property submitted As Nullable(Of Boolean)
    Public Property Destroyed As Nullable(Of Boolean)
    Public Property Invoice_No As String

    Public Overridable Property Drawback As Drawback
    Public Overridable Property User As User

End Class
Partial Public Class Import
    Public Property company As String
    Public Property style As String
    Public Property sizecolor As String
    Public Property s7501 As String
    Public Property port_code As String
    Public Property Origin As String
    Public Property import_date As Date
    Public Property conversion As Decimal
    Public Property tot_val As Nullable(Of Decimal)
    Public Property HMF As Nullable(Of Decimal)
    Public Property units As Nullable(Of Integer)
    Public Property Price As Nullable(Of Decimal)
    Public Property tarrif1 As String
    Public Property tarrif2 As String
    Public Property tarrif3 As String
    Public Property tarrif4 As String
    Public Property kilos1 As String
    Public Property kilos2 As String
    Public Property kilos3 As String
    Public Property kilos4 As String
    Public Property value1 As Nullable(Of Decimal)
    Public Property value2 As Nullable(Of Decimal)
    Public Property value3 As Nullable(Of Decimal)
    Public Property value4 As Nullable(Of Decimal)
    Public Property duty_per_piece As String
    Public Property MPF As Nullable(Of Decimal)
    Public Property UnitsType As String

    Public Overridable Property User As User

End Class
Partial Public Class Status
    Public Property Username As String
    Public Property Path As String
    Public Property Comments As String
    Public Property Approved As Nullable(Of Boolean)
    Public Property stid As Long

End Class
Partial Public Class Tarrif
    Public Property Tarrif_Code As String
    Public Property Description As String
    Public Property Percent_Rate As String
    Public Property Piece_Rate As String
    Public Property Kilo_Rate As String
    Public Property Related_Tarrifs As String

End Class
Partial Public Class User
    Public Property Username As String
    Public Property Password As String
    Public Property Email As String
    Public Property Contact As String
    Public Property Address As String
    Public Property Phone As String
    Public Property Company As String
    Public Property BondedBy As String
    Public Property HowMuch As String
    Public Property ExpDate As String
    Public Property FilerNo As String
    Public Property FilerCode As String
    Public Property irsnumber As String
    Public Property Questionare As Nullable(Of Boolean)
    Public Property PermissionLetter As Nullable(Of Boolean)
    Public Property Agreement As Nullable(Of Boolean)

    Public Overridable Property Exports As ICollection(Of Export) = New HashSet(Of Export)
    Public Overridable Property [Imports] As ICollection(Of Import) = New HashSet(Of Import)

End Class
