//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

public partial class edrawbackEntities : DbContext
{
    public edrawbackEntities()
        : base("name=edrawbackEntities")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public DbSet<Drawback> Drawbacks { get; set; }
    public DbSet<Export> Exports { get; set; }
    public DbSet<Import> Imports { get; set; }
    public DbSet<Status> Status { get; set; }
    public DbSet<Tarrif> Tarrifs { get; set; }
    public DbSet<User> Users { get; set; }
    public DbSet<database_firewall_rules> database_firewall_rules { get; set; }
}
