//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class database_firewall_rules
{
    public int id { get; set; }
    public string name { get; set; }
    public string start_ip_address { get; set; }
    public string end_ip_address { get; set; }
    public System.DateTime create_date { get; set; }
    public System.DateTime modify_date { get; set; }
}

public partial class Drawback
{
    public Drawback()
    {
        this.Exports = new HashSet<Export>();
    }

    public string Drawback_Number { get; set; }
    public string status { get; set; }
    public Nullable<System.DateTime> filed_date { get; set; }

    public virtual ICollection<Export> Exports { get; set; }
}

public partial class Export
{
    public string Company { get; set; }
    public string Style { get; set; }
    public string SizeColor { get; set; }
    public System.DateTime Export_Date { get; set; }
    public string Freight_carrier { get; set; }
    public string Reference_number { get; set; }
    public string Export_Country { get; set; }
    public System.DateTime Import_Date { get; set; }
    public Nullable<int> Units { get; set; }
    public Nullable<decimal> Duty { get; set; }
    public string Drawback_Number { get; set; }
    public Nullable<bool> submitted { get; set; }
    public Nullable<bool> Destroyed { get; set; }
    public string Invoice_No { get; set; }

    public virtual Drawback Drawback { get; set; }
    public virtual User User { get; set; }
}

public partial class Import
{
    public string company { get; set; }
    public string style { get; set; }
    public string sizecolor { get; set; }
    public string s7501 { get; set; }
    public string port_code { get; set; }
    public string Origin { get; set; }
    public System.DateTime import_date { get; set; }
    public decimal conversion { get; set; }
    public Nullable<decimal> tot_val { get; set; }
    public Nullable<decimal> HMF { get; set; }
    public Nullable<int> units { get; set; }
    public Nullable<decimal> Price { get; set; }
    public string tarrif1 { get; set; }
    public string tarrif2 { get; set; }
    public string tarrif3 { get; set; }
    public string tarrif4 { get; set; }
    public string kilos1 { get; set; }
    public string kilos2 { get; set; }
    public string kilos3 { get; set; }
    public string kilos4 { get; set; }
    public Nullable<decimal> value1 { get; set; }
    public Nullable<decimal> value2 { get; set; }
    public Nullable<decimal> value3 { get; set; }
    public Nullable<decimal> value4 { get; set; }
    public string duty_per_piece { get; set; }
    public Nullable<decimal> MPF { get; set; }
    public string UnitsType { get; set; }

    public virtual User User { get; set; }
}

public partial class Status
{
    public string Username { get; set; }
    public string Path { get; set; }
    public string Comments { get; set; }
    public Nullable<bool> Approved { get; set; }
    public long stid { get; set; }
}

public partial class Tarrif
{
    public string Tarrif_Code { get; set; }
    public string Description { get; set; }
    public string Percent_Rate { get; set; }
    public string Piece_Rate { get; set; }
    public string Kilo_Rate { get; set; }
    public string Related_Tarrifs { get; set; }
}

public partial class User
{
    public User()
    {
        this.Exports = new HashSet<Export>();
        this.Imports = new HashSet<Import>();
    }

    public string Username { get; set; }
    public string Password { get; set; }
    public string Email { get; set; }
    public string Contact { get; set; }
    public string Address { get; set; }
    public string Phone { get; set; }
    public string Company { get; set; }
    public string BondedBy { get; set; }
    public string HowMuch { get; set; }
    public string ExpDate { get; set; }
    public string FilerNo { get; set; }
    public string FilerCode { get; set; }
    public string irsnumber { get; set; }
    public Nullable<bool> Questionare { get; set; }
    public Nullable<bool> PermissionLetter { get; set; }
    public Nullable<bool> Agreement { get; set; }

    public virtual ICollection<Export> Exports { get; set; }
    public virtual ICollection<Import> Imports { get; set; }
}
