
'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.ComponentModel
Imports System.Data.EntityClient
Imports System.Data.Objects
Imports System.Data.Objects.DataClasses
Imports System.Linq
Imports System.Runtime.Serialization
Imports System.Xml.Serialization

<Assembly: EdmSchemaAttribute("175d80d4-7f3a-464b-bcd1-d722a321f338")>
#Region "EDM Relationship Metadata"
<Assembly: EdmRelationshipAttribute("DB_9AA143_mendyaModel", "FK_Drawbacks_Drawback_Number", "Drawbacks", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, GetType(DB_9AA143_mendyaModel.Drawback), "Export", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(DB_9AA143_mendyaModel.Export))>
<Assembly: EdmRelationshipAttribute("DB_9AA143_mendyaModel", "Export_Company_FK", "Users", System.Data.Metadata.Edm.RelationshipMultiplicity.One, GetType(DB_9AA143_mendyaModel.User), "Export", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(DB_9AA143_mendyaModel.Export), True)>
<Assembly: EdmRelationshipAttribute("DB_9AA143_mendyaModel", "Import_Company_FK", "Users", System.Data.Metadata.Edm.RelationshipMultiplicity.One, GetType(DB_9AA143_mendyaModel.User), "Import", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(DB_9AA143_mendyaModel.Import), True)>

#End Region

Namespace DB_9AA143_mendyaModel

    #Region "Contexts"
    
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public Partial Class DB_9AA143_mendyaEntities
        Inherits ObjectContext
    
        #Region "Constructors"
    
        ''' <summary>
        ''' Initializes a new DB_9AA143_mendyaEntities object using the connection string found in the 'DB_9AA143_mendyaEntities' section of the application configuration file.
        ''' </summary>
        Public Sub New()
            MyBase.New("name=DB_9AA143_mendyaEntities", "DB_9AA143_mendyaEntities")
            OnContextCreated()
        End Sub
    
        ''' <summary>
        ''' Initialize a new DB_9AA143_mendyaEntities object.
        ''' </summary>
        Public Sub New(ByVal connectionString As String)
            MyBase.New(connectionString, "DB_9AA143_mendyaEntities")
            OnContextCreated()
        End Sub
    
        ''' <summary>
        ''' Initialize a new DB_9AA143_mendyaEntities object.
        ''' </summary>
        Public Sub New(ByVal connection As EntityConnection)
            MyBase.New(connection, "DB_9AA143_mendyaEntities")
            OnContextCreated()
        End Sub
    
        #End Region
    
        #Region "Partial Methods"
    
        Partial Private Sub OnContextCreated()
        End Sub
    
        #End Region
    
        #Region "ObjectSet Properties"
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        Public ReadOnly Property Drawbacks() As ObjectSet(Of Drawback)
            Get
                If (_Drawbacks Is Nothing) Then
                    _Drawbacks = MyBase.CreateObjectSet(Of Drawback)("Drawbacks")
                End If
                Return _Drawbacks
            End Get
        End Property
    
        Private _Drawbacks As ObjectSet(Of Drawback)
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        Public ReadOnly Property Exports() As ObjectSet(Of Export)
            Get
                If (_Exports Is Nothing) Then
                    _Exports = MyBase.CreateObjectSet(Of Export)("Exports")
                End If
                Return _Exports
            End Get
        End Property
    
        Private _Exports As ObjectSet(Of Export)
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        Public ReadOnly Property [Imports]() As ObjectSet(Of Import)
            Get
                If (_Imports Is Nothing) Then
                    _Imports = MyBase.CreateObjectSet(Of Import)("Imports")
                End If
                Return _Imports
            End Get
        End Property
    
        Private _Imports As ObjectSet(Of Import)
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        Public ReadOnly Property Status() As ObjectSet(Of Status)
            Get
                If (_Status Is Nothing) Then
                    _Status = MyBase.CreateObjectSet(Of Status)("Status")
                End If
                Return _Status
            End Get
        End Property
    
        Private _Status As ObjectSet(Of Status)
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        Public ReadOnly Property Tarrifs() As ObjectSet(Of Tarrif)
            Get
                If (_Tarrifs Is Nothing) Then
                    _Tarrifs = MyBase.CreateObjectSet(Of Tarrif)("Tarrifs")
                End If
                Return _Tarrifs
            End Get
        End Property
    
        Private _Tarrifs As ObjectSet(Of Tarrif)
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        Public ReadOnly Property Users() As ObjectSet(Of User)
            Get
                If (_Users Is Nothing) Then
                    _Users = MyBase.CreateObjectSet(Of User)("Users")
                End If
                Return _Users
            End Get
        End Property
    
        Private _Users As ObjectSet(Of User)
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        Public ReadOnly Property database_firewall_rules() As ObjectSet(Of database_firewall_rules)
            Get
                If (_database_firewall_rules Is Nothing) Then
                    _database_firewall_rules = MyBase.CreateObjectSet(Of database_firewall_rules)("database_firewall_rules")
                End If
                Return _database_firewall_rules
            End Get
        End Property
    
        Private _database_firewall_rules As ObjectSet(Of database_firewall_rules)

        #End Region

        #Region "AddTo Methods"
    
        ''' <summary>
        ''' Deprecated Method for adding a new object to the Drawbacks EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
        ''' </summary>
        Public Sub AddToDrawbacks(ByVal drawback As Drawback)
            MyBase.AddObject("Drawbacks", drawback)
        End Sub
    
        ''' <summary>
        ''' Deprecated Method for adding a new object to the Exports EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
        ''' </summary>
        Public Sub AddToExports(ByVal export As Export)
            MyBase.AddObject("Exports", export)
        End Sub
    
        ''' <summary>
        ''' Deprecated Method for adding a new object to the Imports EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
        ''' </summary>
        Public Sub AddToImports(ByVal import As Import)
            MyBase.AddObject("Imports", import)
        End Sub
    
        ''' <summary>
        ''' Deprecated Method for adding a new object to the Status EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
        ''' </summary>
        Public Sub AddToStatus(ByVal status As Status)
            MyBase.AddObject("Status", status)
        End Sub
    
        ''' <summary>
        ''' Deprecated Method for adding a new object to the Tarrifs EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
        ''' </summary>
        Public Sub AddToTarrifs(ByVal tarrif As Tarrif)
            MyBase.AddObject("Tarrifs", tarrif)
        End Sub
    
        ''' <summary>
        ''' Deprecated Method for adding a new object to the Users EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
        ''' </summary>
        Public Sub AddToUsers(ByVal user As User)
            MyBase.AddObject("Users", user)
        End Sub
    
        ''' <summary>
        ''' Deprecated Method for adding a new object to the database_firewall_rules EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
        ''' </summary>
        Public Sub AddTodatabase_firewall_rules(ByVal database_firewall_rules As database_firewall_rules)
            MyBase.AddObject("database_firewall_rules", database_firewall_rules)
        End Sub

        #End Region

    End Class

    #End Region

    #Region "Entities"
    
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmEntityTypeAttribute(NamespaceName:="DB_9AA143_mendyaModel", Name:="database_firewall_rules")>
    <Serializable()>
    <DataContractAttribute(IsReference:=True)>
    Public Partial Class database_firewall_rules
        Inherits EntityObject
        #Region "Factory Method"
    
        ''' <summary>
        ''' Create a new database_firewall_rules object.
        ''' </summary>
        ''' <param name="id">Initial value of the id property.</param>
        ''' <param name="name">Initial value of the name property.</param>
        ''' <param name="start_ip_address">Initial value of the start_ip_address property.</param>
        ''' <param name="end_ip_address">Initial value of the end_ip_address property.</param>
        ''' <param name="create_date">Initial value of the create_date property.</param>
        ''' <param name="modify_date">Initial value of the modify_date property.</param>
        Public Shared Function Createdatabase_firewall_rules(id As Global.System.Int32, name As Global.System.String, start_ip_address As Global.System.String, end_ip_address As Global.System.String, create_date As Global.System.DateTime, modify_date As Global.System.DateTime) As database_firewall_rules
            Dim database_firewall_rules as database_firewall_rules = New database_firewall_rules
            database_firewall_rules.id = id
            database_firewall_rules.name = name
            database_firewall_rules.start_ip_address = start_ip_address
            database_firewall_rules.end_ip_address = end_ip_address
            database_firewall_rules.create_date = create_date
            database_firewall_rules.modify_date = modify_date
            Return database_firewall_rules
        End Function

        #End Region

        #Region "Simple Properties"
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property id() As Global.System.Int32
            Get
                Return _id
            End Get
            Set
                If (_id <> Value) Then
                    OnidChanging(value)
                    ReportPropertyChanging("id")
                    _id = StructuralObject.SetValidValue(value, "id")
                    ReportPropertyChanged("id")
                    OnidChanged()
                End If
            End Set
        End Property
    
        Private _id As Global.System.Int32
        Private Partial Sub OnidChanging(value As Global.System.Int32)
        End Sub
    
        Private Partial Sub OnidChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property name() As Global.System.String
            Get
                Return _name
            End Get
            Set
                If (_name <> Value) Then
                    OnnameChanging(value)
                    ReportPropertyChanging("name")
                    _name = StructuralObject.SetValidValue(value, false, "name")
                    ReportPropertyChanged("name")
                    OnnameChanged()
                End If
            End Set
        End Property
    
        Private _name As Global.System.String
        Private Partial Sub OnnameChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnnameChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property start_ip_address() As Global.System.String
            Get
                Return _start_ip_address
            End Get
            Set
                If (_start_ip_address <> Value) Then
                    Onstart_ip_addressChanging(value)
                    ReportPropertyChanging("start_ip_address")
                    _start_ip_address = StructuralObject.SetValidValue(value, false, "start_ip_address")
                    ReportPropertyChanged("start_ip_address")
                    Onstart_ip_addressChanged()
                End If
            End Set
        End Property
    
        Private _start_ip_address As Global.System.String
        Private Partial Sub Onstart_ip_addressChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub Onstart_ip_addressChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property end_ip_address() As Global.System.String
            Get
                Return _end_ip_address
            End Get
            Set
                If (_end_ip_address <> Value) Then
                    Onend_ip_addressChanging(value)
                    ReportPropertyChanging("end_ip_address")
                    _end_ip_address = StructuralObject.SetValidValue(value, false, "end_ip_address")
                    ReportPropertyChanged("end_ip_address")
                    Onend_ip_addressChanged()
                End If
            End Set
        End Property
    
        Private _end_ip_address As Global.System.String
        Private Partial Sub Onend_ip_addressChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub Onend_ip_addressChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property create_date() As Global.System.DateTime
            Get
                Return _create_date
            End Get
            Set
                If (_create_date <> Value) Then
                    Oncreate_dateChanging(value)
                    ReportPropertyChanging("create_date")
                    _create_date = StructuralObject.SetValidValue(value, "create_date")
                    ReportPropertyChanged("create_date")
                    Oncreate_dateChanged()
                End If
            End Set
        End Property
    
        Private _create_date As Global.System.DateTime
        Private Partial Sub Oncreate_dateChanging(value As Global.System.DateTime)
        End Sub
    
        Private Partial Sub Oncreate_dateChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property modify_date() As Global.System.DateTime
            Get
                Return _modify_date
            End Get
            Set
                If (_modify_date <> Value) Then
                    Onmodify_dateChanging(value)
                    ReportPropertyChanging("modify_date")
                    _modify_date = StructuralObject.SetValidValue(value, "modify_date")
                    ReportPropertyChanged("modify_date")
                    Onmodify_dateChanged()
                End If
            End Set
        End Property
    
        Private _modify_date As Global.System.DateTime
        Private Partial Sub Onmodify_dateChanging(value As Global.System.DateTime)
        End Sub
    
        Private Partial Sub Onmodify_dateChanged()
        End Sub

        #End Region

    End Class
    
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmEntityTypeAttribute(NamespaceName:="DB_9AA143_mendyaModel", Name:="Drawback")>
    <Serializable()>
    <DataContractAttribute(IsReference:=True)>
    Public Partial Class Drawback
        Inherits EntityObject
        #Region "Factory Method"
    
        ''' <summary>
        ''' Create a new Drawback object.
        ''' </summary>
        ''' <param name="drawback_Number">Initial value of the Drawback_Number property.</param>
        Public Shared Function CreateDrawback(drawback_Number As Global.System.String) As Drawback
            Dim drawback as Drawback = New Drawback
            drawback.Drawback_Number = drawback_Number
            Return drawback
        End Function

        #End Region

        #Region "Simple Properties"
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property Drawback_Number() As Global.System.String
            Get
                Return _Drawback_Number
            End Get
            Set
                If (_Drawback_Number <> Value) Then
                    OnDrawback_NumberChanging(value)
                    ReportPropertyChanging("Drawback_Number")
                    _Drawback_Number = StructuralObject.SetValidValue(value, false, "Drawback_Number")
                    ReportPropertyChanged("Drawback_Number")
                    OnDrawback_NumberChanged()
                End If
            End Set
        End Property
    
        Private _Drawback_Number As Global.System.String
        Private Partial Sub OnDrawback_NumberChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnDrawback_NumberChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
        <DataMemberAttribute()>
        Public Property status() As Global.System.String
            Get
                Return _status
            End Get
            Set
                OnstatusChanging(value)
                ReportPropertyChanging("status")
                _status = StructuralObject.SetValidValue(value, true, "status")
                ReportPropertyChanged("status")
                OnstatusChanged()
            End Set
        End Property
    
        Private _status As Global.System.String
        Private Partial Sub OnstatusChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnstatusChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
        <DataMemberAttribute()>
        Public Property filed_date() As Nullable(Of Global.System.DateTime)
            Get
                Return _filed_date
            End Get
            Set
                Onfiled_dateChanging(value)
                ReportPropertyChanging("filed_date")
                _filed_date = StructuralObject.SetValidValue(value, "filed_date")
                ReportPropertyChanged("filed_date")
                Onfiled_dateChanged()
            End Set
        End Property
    
        Private _filed_date As Nullable(Of Global.System.DateTime)
        Private Partial Sub Onfiled_dateChanging(value As Nullable(Of Global.System.DateTime))
        End Sub
    
        Private Partial Sub Onfiled_dateChanged()
        End Sub

        #End Region

        #Region "Navigation Properties"
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <XmlIgnoreAttribute()>
        <SoapIgnoreAttribute()>
        <DataMemberAttribute()>
        <EdmRelationshipNavigationPropertyAttribute("DB_9AA143_mendyaModel", "FK_Drawbacks_Drawback_Number", "Export")>
         Public Property Exports() As EntityCollection(Of Export)
            Get
                Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of Export)("DB_9AA143_mendyaModel.FK_Drawbacks_Drawback_Number", "Export")
            End Get
            Set
                If (Not value Is Nothing)
                    CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of Export)("DB_9AA143_mendyaModel.FK_Drawbacks_Drawback_Number", "Export", value)
                End If
            End Set
        End Property

        #End Region

    End Class
    
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmEntityTypeAttribute(NamespaceName:="DB_9AA143_mendyaModel", Name:="Export")>
    <Serializable()>
    <DataContractAttribute(IsReference:=True)>
    Public Partial Class Export
        Inherits EntityObject
        #Region "Factory Method"
    
        ''' <summary>
        ''' Create a new Export object.
        ''' </summary>
        ''' <param name="company">Initial value of the Company property.</param>
        ''' <param name="style">Initial value of the Style property.</param>
        ''' <param name="sizeColor">Initial value of the SizeColor property.</param>
        ''' <param name="export_Date">Initial value of the Export_Date property.</param>
        ''' <param name="import_Date">Initial value of the Import_Date property.</param>
        Public Shared Function CreateExport(company As Global.System.String, style As Global.System.String, sizeColor As Global.System.String, export_Date As Global.System.DateTime, import_Date As Global.System.DateTime) As Export
            Dim export as Export = New Export
            export.Company = company
            export.Style = style
            export.SizeColor = sizeColor
            export.Export_Date = export_Date
            export.Import_Date = import_Date
            Return export
        End Function

        #End Region

        #Region "Simple Properties"
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property Company() As Global.System.String
            Get
                Return _Company
            End Get
            Set
                If (_Company <> Value) Then
                    OnCompanyChanging(value)
                    ReportPropertyChanging("Company")
                    _Company = StructuralObject.SetValidValue(value, false, "Company")
                    ReportPropertyChanged("Company")
                    OnCompanyChanged()
                End If
            End Set
        End Property
    
        Private _Company As Global.System.String
        Private Partial Sub OnCompanyChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnCompanyChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property Style() As Global.System.String
            Get
                Return _Style
            End Get
            Set
                If (_Style <> Value) Then
                    OnStyleChanging(value)
                    ReportPropertyChanging("Style")
                    _Style = StructuralObject.SetValidValue(value, false, "Style")
                    ReportPropertyChanged("Style")
                    OnStyleChanged()
                End If
            End Set
        End Property
    
        Private _Style As Global.System.String
        Private Partial Sub OnStyleChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnStyleChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property SizeColor() As Global.System.String
            Get
                Return _SizeColor
            End Get
            Set
                If (_SizeColor <> Value) Then
                    OnSizeColorChanging(value)
                    ReportPropertyChanging("SizeColor")
                    _SizeColor = StructuralObject.SetValidValue(value, false, "SizeColor")
                    ReportPropertyChanged("SizeColor")
                    OnSizeColorChanged()
                End If
            End Set
        End Property
    
        Private _SizeColor As Global.System.String
        Private Partial Sub OnSizeColorChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnSizeColorChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property Export_Date() As Global.System.DateTime
            Get
                Return _Export_Date
            End Get
            Set
                If (_Export_Date <> Value) Then
                    OnExport_DateChanging(value)
                    ReportPropertyChanging("Export_Date")
                    _Export_Date = StructuralObject.SetValidValue(value, "Export_Date")
                    ReportPropertyChanged("Export_Date")
                    OnExport_DateChanged()
                End If
            End Set
        End Property
    
        Private _Export_Date As Global.System.DateTime
        Private Partial Sub OnExport_DateChanging(value As Global.System.DateTime)
        End Sub
    
        Private Partial Sub OnExport_DateChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
        <DataMemberAttribute()>
        Public Property Freight_carrier() As Global.System.String
            Get
                Return _Freight_carrier
            End Get
            Set
                OnFreight_carrierChanging(value)
                ReportPropertyChanging("Freight_carrier")
                _Freight_carrier = StructuralObject.SetValidValue(value, true, "Freight_carrier")
                ReportPropertyChanged("Freight_carrier")
                OnFreight_carrierChanged()
            End Set
        End Property
    
        Private _Freight_carrier As Global.System.String
        Private Partial Sub OnFreight_carrierChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnFreight_carrierChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
        <DataMemberAttribute()>
        Public Property Reference_number() As Global.System.String
            Get
                Return _Reference_number
            End Get
            Set
                OnReference_numberChanging(value)
                ReportPropertyChanging("Reference_number")
                _Reference_number = StructuralObject.SetValidValue(value, true, "Reference_number")
                ReportPropertyChanged("Reference_number")
                OnReference_numberChanged()
            End Set
        End Property
    
        Private _Reference_number As Global.System.String
        Private Partial Sub OnReference_numberChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnReference_numberChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
        <DataMemberAttribute()>
        Public Property Export_Country() As Global.System.String
            Get
                Return _Export_Country
            End Get
            Set
                OnExport_CountryChanging(value)
                ReportPropertyChanging("Export_Country")
                _Export_Country = StructuralObject.SetValidValue(value, true, "Export_Country")
                ReportPropertyChanged("Export_Country")
                OnExport_CountryChanged()
            End Set
        End Property
    
        Private _Export_Country As Global.System.String
        Private Partial Sub OnExport_CountryChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnExport_CountryChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property Import_Date() As Global.System.DateTime
            Get
                Return _Import_Date
            End Get
            Set
                If (_Import_Date <> Value) Then
                    OnImport_DateChanging(value)
                    ReportPropertyChanging("Import_Date")
                    _Import_Date = StructuralObject.SetValidValue(value, "Import_Date")
                    ReportPropertyChanged("Import_Date")
                    OnImport_DateChanged()
                End If
            End Set
        End Property
    
        Private _Import_Date As Global.System.DateTime
        Private Partial Sub OnImport_DateChanging(value As Global.System.DateTime)
        End Sub
    
        Private Partial Sub OnImport_DateChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
        <DataMemberAttribute()>
        Public Property Units() As Nullable(Of Global.System.Int32)
            Get
                Return _Units
            End Get
            Set
                OnUnitsChanging(value)
                ReportPropertyChanging("Units")
                _Units = StructuralObject.SetValidValue(value, "Units")
                ReportPropertyChanged("Units")
                OnUnitsChanged()
            End Set
        End Property
    
        Private _Units As Nullable(Of Global.System.Int32)
        Private Partial Sub OnUnitsChanging(value As Nullable(Of Global.System.Int32))
        End Sub
    
        Private Partial Sub OnUnitsChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
        <DataMemberAttribute()>
        Public Property Duty() As Nullable(Of Global.System.Decimal)
            Get
                Return _Duty
            End Get
            Set
                OnDutyChanging(value)
                ReportPropertyChanging("Duty")
                _Duty = StructuralObject.SetValidValue(value, "Duty")
                ReportPropertyChanged("Duty")
                OnDutyChanged()
            End Set
        End Property
    
        Private _Duty As Nullable(Of Global.System.Decimal)
        Private Partial Sub OnDutyChanging(value As Nullable(Of Global.System.Decimal))
        End Sub
    
        Private Partial Sub OnDutyChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
        <DataMemberAttribute()>
        Public Property submitted() As Nullable(Of Global.System.Boolean)
            Get
                Return _submitted
            End Get
            Set
                OnsubmittedChanging(value)
                ReportPropertyChanging("submitted")
                _submitted = StructuralObject.SetValidValue(value, "submitted")
                ReportPropertyChanged("submitted")
                OnsubmittedChanged()
            End Set
        End Property
    
        Private _submitted As Nullable(Of Global.System.Boolean)
        Private Partial Sub OnsubmittedChanging(value As Nullable(Of Global.System.Boolean))
        End Sub
    
        Private Partial Sub OnsubmittedChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
        <DataMemberAttribute()>
        Public Property Destroyed() As Nullable(Of Global.System.Boolean)
            Get
                Return _Destroyed
            End Get
            Set
                OnDestroyedChanging(value)
                ReportPropertyChanging("Destroyed")
                _Destroyed = StructuralObject.SetValidValue(value, "Destroyed")
                ReportPropertyChanged("Destroyed")
                OnDestroyedChanged()
            End Set
        End Property
    
        Private _Destroyed As Nullable(Of Global.System.Boolean)
        Private Partial Sub OnDestroyedChanging(value As Nullable(Of Global.System.Boolean))
        End Sub
    
        Private Partial Sub OnDestroyedChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
        <DataMemberAttribute()>
        Public Property Invoice_No() As Global.System.String
            Get
                Return _Invoice_No
            End Get
            Set
                OnInvoice_NoChanging(value)
                ReportPropertyChanging("Invoice_No")
                _Invoice_No = StructuralObject.SetValidValue(value, true, "Invoice_No")
                ReportPropertyChanged("Invoice_No")
                OnInvoice_NoChanged()
            End Set
        End Property
    
        Private _Invoice_No As Global.System.String
        Private Partial Sub OnInvoice_NoChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnInvoice_NoChanged()
        End Sub

        #End Region

        #Region "Navigation Properties"
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <XmlIgnoreAttribute()>
        <SoapIgnoreAttribute()>
        <DataMemberAttribute()>
        <EdmRelationshipNavigationPropertyAttribute("DB_9AA143_mendyaModel", "FK_Drawbacks_Drawback_Number", "Drawbacks")>
        Public Property Drawback() As Drawback
            Get
                Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Drawback)("DB_9AA143_mendyaModel.FK_Drawbacks_Drawback_Number", "Drawbacks").Value
            End Get
            Set
                CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Drawback)("DB_9AA143_mendyaModel.FK_Drawbacks_Drawback_Number", "Drawbacks").Value = value
            End Set
        End Property
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <BrowsableAttribute(False)>
        <DataMemberAttribute()>
        Public Property DrawbackReference() As EntityReference(Of Drawback)
            Get
                Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Drawback)("DB_9AA143_mendyaModel.FK_Drawbacks_Drawback_Number", "Drawbacks")
            End Get
            Set
                If (Not value Is Nothing)
                    CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of Drawback)("DB_9AA143_mendyaModel.FK_Drawbacks_Drawback_Number", "Drawbacks", value)
                End If
            End Set
        End Property
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <XmlIgnoreAttribute()>
        <SoapIgnoreAttribute()>
        <DataMemberAttribute()>
        <EdmRelationshipNavigationPropertyAttribute("DB_9AA143_mendyaModel", "Export_Company_FK", "Users")>
        Public Property User() As User
            Get
                Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of User)("DB_9AA143_mendyaModel.Export_Company_FK", "Users").Value
            End Get
            Set
                CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of User)("DB_9AA143_mendyaModel.Export_Company_FK", "Users").Value = value
            End Set
        End Property
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <BrowsableAttribute(False)>
        <DataMemberAttribute()>
        Public Property UserReference() As EntityReference(Of User)
            Get
                Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of User)("DB_9AA143_mendyaModel.Export_Company_FK", "Users")
            End Get
            Set
                If (Not value Is Nothing)
                    CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of User)("DB_9AA143_mendyaModel.Export_Company_FK", "Users", value)
                End If
            End Set
        End Property

        #End Region

    End Class
    
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmEntityTypeAttribute(NamespaceName:="DB_9AA143_mendyaModel", Name:="Import")>
    <Serializable()>
    <DataContractAttribute(IsReference:=True)>
    Public Partial Class Import
        Inherits EntityObject
        #Region "Factory Method"
    
        ''' <summary>
        ''' Create a new Import object.
        ''' </summary>
        ''' <param name="company">Initial value of the company property.</param>
        ''' <param name="style">Initial value of the style property.</param>
        ''' <param name="sizecolor">Initial value of the sizecolor property.</param>
        ''' <param name="import_date">Initial value of the import_date property.</param>
        ''' <param name="conversion">Initial value of the conversion property.</param>
        Public Shared Function CreateImport(company As Global.System.String, style As Global.System.String, sizecolor As Global.System.String, import_date As Global.System.DateTime, conversion As Global.System.Decimal) As Import
            Dim import as Import = New Import
            import.company = company
            import.style = style
            import.sizecolor = sizecolor
            import.import_date = import_date
            import.conversion = conversion
            Return import
        End Function

        #End Region

        #Region "Simple Properties"
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property company() As Global.System.String
            Get
                Return _company
            End Get
            Set
                If (_company <> Value) Then
                    OncompanyChanging(value)
                    ReportPropertyChanging("company")
                    _company = StructuralObject.SetValidValue(value, false, "company")
                    ReportPropertyChanged("company")
                    OncompanyChanged()
                End If
            End Set
        End Property
    
        Private _company As Global.System.String
        Private Partial Sub OncompanyChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OncompanyChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property style() As Global.System.String
            Get
                Return _style
            End Get
            Set
                If (_style <> Value) Then
                    OnstyleChanging(value)
                    ReportPropertyChanging("style")
                    _style = StructuralObject.SetValidValue(value, false, "style")
                    ReportPropertyChanged("style")
                    OnstyleChanged()
                End If
            End Set
        End Property
    
        Private _style As Global.System.String
        Private Partial Sub OnstyleChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnstyleChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property sizecolor() As Global.System.String
            Get
                Return _sizecolor
            End Get
            Set
                If (_sizecolor <> Value) Then
                    OnsizecolorChanging(value)
                    ReportPropertyChanging("sizecolor")
                    _sizecolor = StructuralObject.SetValidValue(value, false, "sizecolor")
                    ReportPropertyChanged("sizecolor")
                    OnsizecolorChanged()
                End If
            End Set
        End Property
    
        Private _sizecolor As Global.System.String
        Private Partial Sub OnsizecolorChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnsizecolorChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
        <DataMemberAttribute()>
        Public Property s7501() As Global.System.String
            Get
                Return _s7501
            End Get
            Set
                Ons7501Changing(value)
                ReportPropertyChanging("s7501")
                _s7501 = StructuralObject.SetValidValue(value, true, "s7501")
                ReportPropertyChanged("s7501")
                Ons7501Changed()
            End Set
        End Property
    
        Private _s7501 As Global.System.String
        Private Partial Sub Ons7501Changing(value As Global.System.String)
        End Sub
    
        Private Partial Sub Ons7501Changed()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
        <DataMemberAttribute()>
        Public Property port_code() As Global.System.String
            Get
                Return _port_code
            End Get
            Set
                Onport_codeChanging(value)
                ReportPropertyChanging("port_code")
                _port_code = StructuralObject.SetValidValue(value, true, "port_code")
                ReportPropertyChanged("port_code")
                Onport_codeChanged()
            End Set
        End Property
    
        Private _port_code As Global.System.String
        Private Partial Sub Onport_codeChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub Onport_codeChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
        <DataMemberAttribute()>
        Public Property Origin() As Global.System.String
            Get
                Return _Origin
            End Get
            Set
                OnOriginChanging(value)
                ReportPropertyChanging("Origin")
                _Origin = StructuralObject.SetValidValue(value, true, "Origin")
                ReportPropertyChanged("Origin")
                OnOriginChanged()
            End Set
        End Property
    
        Private _Origin As Global.System.String
        Private Partial Sub OnOriginChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnOriginChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property import_date() As Global.System.DateTime
            Get
                Return _import_date
            End Get
            Set
                If (_import_date <> Value) Then
                    Onimport_dateChanging(value)
                    ReportPropertyChanging("import_date")
                    _import_date = StructuralObject.SetValidValue(value, "import_date")
                    ReportPropertyChanged("import_date")
                    Onimport_dateChanged()
                End If
            End Set
        End Property
    
        Private _import_date As Global.System.DateTime
        Private Partial Sub Onimport_dateChanging(value As Global.System.DateTime)
        End Sub
    
        Private Partial Sub Onimport_dateChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property conversion() As Global.System.Decimal
            Get
                Return _conversion
            End Get
            Set
                OnconversionChanging(value)
                ReportPropertyChanging("conversion")
                _conversion = StructuralObject.SetValidValue(value, "conversion")
                ReportPropertyChanged("conversion")
                OnconversionChanged()
            End Set
        End Property
    
        Private _conversion As Global.System.Decimal
        Private Partial Sub OnconversionChanging(value As Global.System.Decimal)
        End Sub
    
        Private Partial Sub OnconversionChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
        <DataMemberAttribute()>
        Public Property tot_val() As Nullable(Of Global.System.Decimal)
            Get
                Return _tot_val
            End Get
            Set
                Ontot_valChanging(value)
                ReportPropertyChanging("tot_val")
                _tot_val = StructuralObject.SetValidValue(value, "tot_val")
                ReportPropertyChanged("tot_val")
                Ontot_valChanged()
            End Set
        End Property
    
        Private _tot_val As Nullable(Of Global.System.Decimal)
        Private Partial Sub Ontot_valChanging(value As Nullable(Of Global.System.Decimal))
        End Sub
    
        Private Partial Sub Ontot_valChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
        <DataMemberAttribute()>
        Public Property HMF() As Nullable(Of Global.System.Decimal)
            Get
                Return _HMF
            End Get
            Set
                OnHMFChanging(value)
                ReportPropertyChanging("HMF")
                _HMF = StructuralObject.SetValidValue(value, "HMF")
                ReportPropertyChanged("HMF")
                OnHMFChanged()
            End Set
        End Property
    
        Private _HMF As Nullable(Of Global.System.Decimal)
        Private Partial Sub OnHMFChanging(value As Nullable(Of Global.System.Decimal))
        End Sub
    
        Private Partial Sub OnHMFChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
        <DataMemberAttribute()>
        Public Property units() As Nullable(Of Global.System.Int32)
            Get
                Return _units
            End Get
            Set
                OnunitsChanging(value)
                ReportPropertyChanging("units")
                _units = StructuralObject.SetValidValue(value, "units")
                ReportPropertyChanged("units")
                OnunitsChanged()
            End Set
        End Property
    
        Private _units As Nullable(Of Global.System.Int32)
        Private Partial Sub OnunitsChanging(value As Nullable(Of Global.System.Int32))
        End Sub
    
        Private Partial Sub OnunitsChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
        <DataMemberAttribute()>
        Public Property Price() As Nullable(Of Global.System.Decimal)
            Get
                Return _Price
            End Get
            Set
                OnPriceChanging(value)
                ReportPropertyChanging("Price")
                _Price = StructuralObject.SetValidValue(value, "Price")
                ReportPropertyChanged("Price")
                OnPriceChanged()
            End Set
        End Property
    
        Private _Price As Nullable(Of Global.System.Decimal)
        Private Partial Sub OnPriceChanging(value As Nullable(Of Global.System.Decimal))
        End Sub
    
        Private Partial Sub OnPriceChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
        <DataMemberAttribute()>
        Public Property tarrif1() As Global.System.String
            Get
                Return _tarrif1
            End Get
            Set
                Ontarrif1Changing(value)
                ReportPropertyChanging("tarrif1")
                _tarrif1 = StructuralObject.SetValidValue(value, true, "tarrif1")
                ReportPropertyChanged("tarrif1")
                Ontarrif1Changed()
            End Set
        End Property
    
        Private _tarrif1 As Global.System.String
        Private Partial Sub Ontarrif1Changing(value As Global.System.String)
        End Sub
    
        Private Partial Sub Ontarrif1Changed()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
        <DataMemberAttribute()>
        Public Property tarrif2() As Global.System.String
            Get
                Return _tarrif2
            End Get
            Set
                Ontarrif2Changing(value)
                ReportPropertyChanging("tarrif2")
                _tarrif2 = StructuralObject.SetValidValue(value, true, "tarrif2")
                ReportPropertyChanged("tarrif2")
                Ontarrif2Changed()
            End Set
        End Property
    
        Private _tarrif2 As Global.System.String
        Private Partial Sub Ontarrif2Changing(value As Global.System.String)
        End Sub
    
        Private Partial Sub Ontarrif2Changed()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
        <DataMemberAttribute()>
        Public Property tarrif3() As Global.System.String
            Get
                Return _tarrif3
            End Get
            Set
                Ontarrif3Changing(value)
                ReportPropertyChanging("tarrif3")
                _tarrif3 = StructuralObject.SetValidValue(value, true, "tarrif3")
                ReportPropertyChanged("tarrif3")
                Ontarrif3Changed()
            End Set
        End Property
    
        Private _tarrif3 As Global.System.String
        Private Partial Sub Ontarrif3Changing(value As Global.System.String)
        End Sub
    
        Private Partial Sub Ontarrif3Changed()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
        <DataMemberAttribute()>
        Public Property tarrif4() As Global.System.String
            Get
                Return _tarrif4
            End Get
            Set
                Ontarrif4Changing(value)
                ReportPropertyChanging("tarrif4")
                _tarrif4 = StructuralObject.SetValidValue(value, true, "tarrif4")
                ReportPropertyChanged("tarrif4")
                Ontarrif4Changed()
            End Set
        End Property
    
        Private _tarrif4 As Global.System.String
        Private Partial Sub Ontarrif4Changing(value As Global.System.String)
        End Sub
    
        Private Partial Sub Ontarrif4Changed()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
        <DataMemberAttribute()>
        Public Property kilos1() As Global.System.String
            Get
                Return _kilos1
            End Get
            Set
                Onkilos1Changing(value)
                ReportPropertyChanging("kilos1")
                _kilos1 = StructuralObject.SetValidValue(value, true, "kilos1")
                ReportPropertyChanged("kilos1")
                Onkilos1Changed()
            End Set
        End Property
    
        Private _kilos1 As Global.System.String
        Private Partial Sub Onkilos1Changing(value As Global.System.String)
        End Sub
    
        Private Partial Sub Onkilos1Changed()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
        <DataMemberAttribute()>
        Public Property kilos2() As Global.System.String
            Get
                Return _kilos2
            End Get
            Set
                Onkilos2Changing(value)
                ReportPropertyChanging("kilos2")
                _kilos2 = StructuralObject.SetValidValue(value, true, "kilos2")
                ReportPropertyChanged("kilos2")
                Onkilos2Changed()
            End Set
        End Property
    
        Private _kilos2 As Global.System.String
        Private Partial Sub Onkilos2Changing(value As Global.System.String)
        End Sub
    
        Private Partial Sub Onkilos2Changed()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
        <DataMemberAttribute()>
        Public Property kilos3() As Global.System.String
            Get
                Return _kilos3
            End Get
            Set
                Onkilos3Changing(value)
                ReportPropertyChanging("kilos3")
                _kilos3 = StructuralObject.SetValidValue(value, true, "kilos3")
                ReportPropertyChanged("kilos3")
                Onkilos3Changed()
            End Set
        End Property
    
        Private _kilos3 As Global.System.String
        Private Partial Sub Onkilos3Changing(value As Global.System.String)
        End Sub
    
        Private Partial Sub Onkilos3Changed()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
        <DataMemberAttribute()>
        Public Property kilos4() As Global.System.String
            Get
                Return _kilos4
            End Get
            Set
                Onkilos4Changing(value)
                ReportPropertyChanging("kilos4")
                _kilos4 = StructuralObject.SetValidValue(value, true, "kilos4")
                ReportPropertyChanged("kilos4")
                Onkilos4Changed()
            End Set
        End Property
    
        Private _kilos4 As Global.System.String
        Private Partial Sub Onkilos4Changing(value As Global.System.String)
        End Sub
    
        Private Partial Sub Onkilos4Changed()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
        <DataMemberAttribute()>
        Public Property value1() As Nullable(Of Global.System.Decimal)
            Get
                Return _value1
            End Get
            Set
                Onvalue1Changing(value)
                ReportPropertyChanging("value1")
                _value1 = StructuralObject.SetValidValue(value, "value1")
                ReportPropertyChanged("value1")
                Onvalue1Changed()
            End Set
        End Property
    
        Private _value1 As Nullable(Of Global.System.Decimal)
        Private Partial Sub Onvalue1Changing(value As Nullable(Of Global.System.Decimal))
        End Sub
    
        Private Partial Sub Onvalue1Changed()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
        <DataMemberAttribute()>
        Public Property value2() As Nullable(Of Global.System.Decimal)
            Get
                Return _value2
            End Get
            Set
                Onvalue2Changing(value)
                ReportPropertyChanging("value2")
                _value2 = StructuralObject.SetValidValue(value, "value2")
                ReportPropertyChanged("value2")
                Onvalue2Changed()
            End Set
        End Property
    
        Private _value2 As Nullable(Of Global.System.Decimal)
        Private Partial Sub Onvalue2Changing(value As Nullable(Of Global.System.Decimal))
        End Sub
    
        Private Partial Sub Onvalue2Changed()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
        <DataMemberAttribute()>
        Public Property value3() As Nullable(Of Global.System.Decimal)
            Get
                Return _value3
            End Get
            Set
                Onvalue3Changing(value)
                ReportPropertyChanging("value3")
                _value3 = StructuralObject.SetValidValue(value, "value3")
                ReportPropertyChanged("value3")
                Onvalue3Changed()
            End Set
        End Property
    
        Private _value3 As Nullable(Of Global.System.Decimal)
        Private Partial Sub Onvalue3Changing(value As Nullable(Of Global.System.Decimal))
        End Sub
    
        Private Partial Sub Onvalue3Changed()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
        <DataMemberAttribute()>
        Public Property value4() As Nullable(Of Global.System.Decimal)
            Get
                Return _value4
            End Get
            Set
                Onvalue4Changing(value)
                ReportPropertyChanging("value4")
                _value4 = StructuralObject.SetValidValue(value, "value4")
                ReportPropertyChanged("value4")
                Onvalue4Changed()
            End Set
        End Property
    
        Private _value4 As Nullable(Of Global.System.Decimal)
        Private Partial Sub Onvalue4Changing(value As Nullable(Of Global.System.Decimal))
        End Sub
    
        Private Partial Sub Onvalue4Changed()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
        <DataMemberAttribute()>
        Public Property duty_per_piece() As Global.System.String
            Get
                Return _duty_per_piece
            End Get
            Set
                Onduty_per_pieceChanging(value)
                ReportPropertyChanging("duty_per_piece")
                _duty_per_piece = StructuralObject.SetValidValue(value, true, "duty_per_piece")
                ReportPropertyChanged("duty_per_piece")
                Onduty_per_pieceChanged()
            End Set
        End Property
    
        Private _duty_per_piece As Global.System.String
        Private Partial Sub Onduty_per_pieceChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub Onduty_per_pieceChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
        <DataMemberAttribute()>
        Public Property MPF() As Nullable(Of Global.System.Decimal)
            Get
                Return _MPF
            End Get
            Set
                OnMPFChanging(value)
                ReportPropertyChanging("MPF")
                _MPF = StructuralObject.SetValidValue(value, "MPF")
                ReportPropertyChanged("MPF")
                OnMPFChanged()
            End Set
        End Property
    
        Private _MPF As Nullable(Of Global.System.Decimal)
        Private Partial Sub OnMPFChanging(value As Nullable(Of Global.System.Decimal))
        End Sub
    
        Private Partial Sub OnMPFChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
        <DataMemberAttribute()>
        Public Property UnitsType() As Global.System.String
            Get
                Return _UnitsType
            End Get
            Set
                OnUnitsTypeChanging(value)
                ReportPropertyChanging("UnitsType")
                _UnitsType = StructuralObject.SetValidValue(value, true, "UnitsType")
                ReportPropertyChanged("UnitsType")
                OnUnitsTypeChanged()
            End Set
        End Property
    
        Private _UnitsType As Global.System.String
        Private Partial Sub OnUnitsTypeChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnUnitsTypeChanged()
        End Sub

        #End Region

        #Region "Navigation Properties"
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <XmlIgnoreAttribute()>
        <SoapIgnoreAttribute()>
        <DataMemberAttribute()>
        <EdmRelationshipNavigationPropertyAttribute("DB_9AA143_mendyaModel", "Import_Company_FK", "Users")>
        Public Property User() As User
            Get
                Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of User)("DB_9AA143_mendyaModel.Import_Company_FK", "Users").Value
            End Get
            Set
                CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of User)("DB_9AA143_mendyaModel.Import_Company_FK", "Users").Value = value
            End Set
        End Property
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <BrowsableAttribute(False)>
        <DataMemberAttribute()>
        Public Property UserReference() As EntityReference(Of User)
            Get
                Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of User)("DB_9AA143_mendyaModel.Import_Company_FK", "Users")
            End Get
            Set
                If (Not value Is Nothing)
                    CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of User)("DB_9AA143_mendyaModel.Import_Company_FK", "Users", value)
                End If
            End Set
        End Property

        #End Region

    End Class
    
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmEntityTypeAttribute(NamespaceName:="DB_9AA143_mendyaModel", Name:="Status")>
    <Serializable()>
    <DataContractAttribute(IsReference:=True)>
    Public Partial Class Status
        Inherits EntityObject
        #Region "Factory Method"
    
        ''' <summary>
        ''' Create a new Status object.
        ''' </summary>
        ''' <param name="username">Initial value of the Username property.</param>
        ''' <param name="path">Initial value of the Path property.</param>
        ''' <param name="comments">Initial value of the Comments property.</param>
        ''' <param name="stid">Initial value of the stid property.</param>
        Public Shared Function CreateStatus(username As Global.System.String, path As Global.System.String, comments As Global.System.String, stid As Global.System.Int64) As Status
            Dim status as Status = New Status
            status.Username = username
            status.Path = path
            status.Comments = comments
            status.stid = stid
            Return status
        End Function

        #End Region

        #Region "Simple Properties"
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property Username() As Global.System.String
            Get
                Return _Username
            End Get
            Set
                OnUsernameChanging(value)
                ReportPropertyChanging("Username")
                _Username = StructuralObject.SetValidValue(value, false, "Username")
                ReportPropertyChanged("Username")
                OnUsernameChanged()
            End Set
        End Property
    
        Private _Username As Global.System.String
        Private Partial Sub OnUsernameChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnUsernameChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property Path() As Global.System.String
            Get
                Return _Path
            End Get
            Set
                OnPathChanging(value)
                ReportPropertyChanging("Path")
                _Path = StructuralObject.SetValidValue(value, false, "Path")
                ReportPropertyChanged("Path")
                OnPathChanged()
            End Set
        End Property
    
        Private _Path As Global.System.String
        Private Partial Sub OnPathChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnPathChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property Comments() As Global.System.String
            Get
                Return _Comments
            End Get
            Set
                OnCommentsChanging(value)
                ReportPropertyChanging("Comments")
                _Comments = StructuralObject.SetValidValue(value, false, "Comments")
                ReportPropertyChanged("Comments")
                OnCommentsChanged()
            End Set
        End Property
    
        Private _Comments As Global.System.String
        Private Partial Sub OnCommentsChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnCommentsChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
        <DataMemberAttribute()>
        Public Property Approved() As Nullable(Of Global.System.Boolean)
            Get
                Return _Approved
            End Get
            Set
                OnApprovedChanging(value)
                ReportPropertyChanging("Approved")
                _Approved = StructuralObject.SetValidValue(value, "Approved")
                ReportPropertyChanged("Approved")
                OnApprovedChanged()
            End Set
        End Property
    
        Private _Approved As Nullable(Of Global.System.Boolean)
        Private Partial Sub OnApprovedChanging(value As Nullable(Of Global.System.Boolean))
        End Sub
    
        Private Partial Sub OnApprovedChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property stid() As Global.System.Int64
            Get
                Return _stid
            End Get
            Set
                If (_stid <> Value) Then
                    OnstidChanging(value)
                    ReportPropertyChanging("stid")
                    _stid = StructuralObject.SetValidValue(value, "stid")
                    ReportPropertyChanged("stid")
                    OnstidChanged()
                End If
            End Set
        End Property
    
        Private _stid As Global.System.Int64
        Private Partial Sub OnstidChanging(value As Global.System.Int64)
        End Sub
    
        Private Partial Sub OnstidChanged()
        End Sub

        #End Region

    End Class
    
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmEntityTypeAttribute(NamespaceName:="DB_9AA143_mendyaModel", Name:="Tarrif")>
    <Serializable()>
    <DataContractAttribute(IsReference:=True)>
    Public Partial Class Tarrif
        Inherits EntityObject
        #Region "Factory Method"
    
        ''' <summary>
        ''' Create a new Tarrif object.
        ''' </summary>
        ''' <param name="tarrif_Code">Initial value of the Tarrif_Code property.</param>
        Public Shared Function CreateTarrif(tarrif_Code As Global.System.String) As Tarrif
            Dim tarrif as Tarrif = New Tarrif
            tarrif.Tarrif_Code = tarrif_Code
            Return tarrif
        End Function

        #End Region

        #Region "Simple Properties"
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property Tarrif_Code() As Global.System.String
            Get
                Return _Tarrif_Code
            End Get
            Set
                If (_Tarrif_Code <> Value) Then
                    OnTarrif_CodeChanging(value)
                    ReportPropertyChanging("Tarrif_Code")
                    _Tarrif_Code = StructuralObject.SetValidValue(value, false, "Tarrif_Code")
                    ReportPropertyChanged("Tarrif_Code")
                    OnTarrif_CodeChanged()
                End If
            End Set
        End Property
    
        Private _Tarrif_Code As Global.System.String
        Private Partial Sub OnTarrif_CodeChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnTarrif_CodeChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
        <DataMemberAttribute()>
        Public Property Description() As Global.System.String
            Get
                Return _Description
            End Get
            Set
                OnDescriptionChanging(value)
                ReportPropertyChanging("Description")
                _Description = StructuralObject.SetValidValue(value, true, "Description")
                ReportPropertyChanged("Description")
                OnDescriptionChanged()
            End Set
        End Property
    
        Private _Description As Global.System.String
        Private Partial Sub OnDescriptionChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnDescriptionChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
        <DataMemberAttribute()>
        Public Property Percent_Rate() As Global.System.String
            Get
                Return _Percent_Rate
            End Get
            Set
                OnPercent_RateChanging(value)
                ReportPropertyChanging("Percent_Rate")
                _Percent_Rate = StructuralObject.SetValidValue(value, true, "Percent_Rate")
                ReportPropertyChanged("Percent_Rate")
                OnPercent_RateChanged()
            End Set
        End Property
    
        Private _Percent_Rate As Global.System.String
        Private Partial Sub OnPercent_RateChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnPercent_RateChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
        <DataMemberAttribute()>
        Public Property Piece_Rate() As Global.System.String
            Get
                Return _Piece_Rate
            End Get
            Set
                OnPiece_RateChanging(value)
                ReportPropertyChanging("Piece_Rate")
                _Piece_Rate = StructuralObject.SetValidValue(value, true, "Piece_Rate")
                ReportPropertyChanged("Piece_Rate")
                OnPiece_RateChanged()
            End Set
        End Property
    
        Private _Piece_Rate As Global.System.String
        Private Partial Sub OnPiece_RateChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnPiece_RateChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
        <DataMemberAttribute()>
        Public Property Kilo_Rate() As Global.System.String
            Get
                Return _Kilo_Rate
            End Get
            Set
                OnKilo_RateChanging(value)
                ReportPropertyChanging("Kilo_Rate")
                _Kilo_Rate = StructuralObject.SetValidValue(value, true, "Kilo_Rate")
                ReportPropertyChanged("Kilo_Rate")
                OnKilo_RateChanged()
            End Set
        End Property
    
        Private _Kilo_Rate As Global.System.String
        Private Partial Sub OnKilo_RateChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnKilo_RateChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
        <DataMemberAttribute()>
        Public Property Related_Tarrifs() As Global.System.String
            Get
                Return _Related_Tarrifs
            End Get
            Set
                OnRelated_TarrifsChanging(value)
                ReportPropertyChanging("Related_Tarrifs")
                _Related_Tarrifs = StructuralObject.SetValidValue(value, true, "Related_Tarrifs")
                ReportPropertyChanged("Related_Tarrifs")
                OnRelated_TarrifsChanged()
            End Set
        End Property
    
        Private _Related_Tarrifs As Global.System.String
        Private Partial Sub OnRelated_TarrifsChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnRelated_TarrifsChanged()
        End Sub

        #End Region

    End Class
    
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmEntityTypeAttribute(NamespaceName:="DB_9AA143_mendyaModel", Name:="User")>
    <Serializable()>
    <DataContractAttribute(IsReference:=True)>
    Public Partial Class User
        Inherits EntityObject
        #Region "Factory Method"
    
        ''' <summary>
        ''' Create a new User object.
        ''' </summary>
        ''' <param name="username">Initial value of the Username property.</param>
        ''' <param name="password">Initial value of the Password property.</param>
        ''' <param name="email">Initial value of the Email property.</param>
        ''' <param name="contact">Initial value of the Contact property.</param>
        ''' <param name="address">Initial value of the Address property.</param>
        ''' <param name="phone">Initial value of the Phone property.</param>
        ''' <param name="company">Initial value of the Company property.</param>
        ''' <param name="bondedBy">Initial value of the BondedBy property.</param>
        ''' <param name="howMuch">Initial value of the HowMuch property.</param>
        ''' <param name="expDate">Initial value of the ExpDate property.</param>
        Public Shared Function CreateUser(username As Global.System.String, password As Global.System.String, email As Global.System.String, contact As Global.System.String, address As Global.System.String, phone As Global.System.String, company As Global.System.String, bondedBy As Global.System.String, howMuch As Global.System.String, expDate As Global.System.String) As User
            Dim user as User = New User
            user.Username = username
            user.Password = password
            user.Email = email
            user.Contact = contact
            user.Address = address
            user.Phone = phone
            user.Company = company
            user.BondedBy = bondedBy
            user.HowMuch = howMuch
            user.ExpDate = expDate
            Return user
        End Function

        #End Region

        #Region "Simple Properties"
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property Username() As Global.System.String
            Get
                Return _Username
            End Get
            Set
                If (_Username <> Value) Then
                    OnUsernameChanging(value)
                    ReportPropertyChanging("Username")
                    _Username = StructuralObject.SetValidValue(value, false, "Username")
                    ReportPropertyChanged("Username")
                    OnUsernameChanged()
                End If
            End Set
        End Property
    
        Private _Username As Global.System.String
        Private Partial Sub OnUsernameChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnUsernameChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property Password() As Global.System.String
            Get
                Return _Password
            End Get
            Set
                OnPasswordChanging(value)
                ReportPropertyChanging("Password")
                _Password = StructuralObject.SetValidValue(value, false, "Password")
                ReportPropertyChanged("Password")
                OnPasswordChanged()
            End Set
        End Property
    
        Private _Password As Global.System.String
        Private Partial Sub OnPasswordChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnPasswordChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property Email() As Global.System.String
            Get
                Return _Email
            End Get
            Set
                OnEmailChanging(value)
                ReportPropertyChanging("Email")
                _Email = StructuralObject.SetValidValue(value, false, "Email")
                ReportPropertyChanged("Email")
                OnEmailChanged()
            End Set
        End Property
    
        Private _Email As Global.System.String
        Private Partial Sub OnEmailChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnEmailChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property Contact() As Global.System.String
            Get
                Return _Contact
            End Get
            Set
                OnContactChanging(value)
                ReportPropertyChanging("Contact")
                _Contact = StructuralObject.SetValidValue(value, false, "Contact")
                ReportPropertyChanged("Contact")
                OnContactChanged()
            End Set
        End Property
    
        Private _Contact As Global.System.String
        Private Partial Sub OnContactChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnContactChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property Address() As Global.System.String
            Get
                Return _Address
            End Get
            Set
                OnAddressChanging(value)
                ReportPropertyChanging("Address")
                _Address = StructuralObject.SetValidValue(value, false, "Address")
                ReportPropertyChanged("Address")
                OnAddressChanged()
            End Set
        End Property
    
        Private _Address As Global.System.String
        Private Partial Sub OnAddressChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnAddressChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property Phone() As Global.System.String
            Get
                Return _Phone
            End Get
            Set
                OnPhoneChanging(value)
                ReportPropertyChanging("Phone")
                _Phone = StructuralObject.SetValidValue(value, false, "Phone")
                ReportPropertyChanged("Phone")
                OnPhoneChanged()
            End Set
        End Property
    
        Private _Phone As Global.System.String
        Private Partial Sub OnPhoneChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnPhoneChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property Company() As Global.System.String
            Get
                Return _Company
            End Get
            Set
                OnCompanyChanging(value)
                ReportPropertyChanging("Company")
                _Company = StructuralObject.SetValidValue(value, false, "Company")
                ReportPropertyChanged("Company")
                OnCompanyChanged()
            End Set
        End Property
    
        Private _Company As Global.System.String
        Private Partial Sub OnCompanyChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnCompanyChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property BondedBy() As Global.System.String
            Get
                Return _BondedBy
            End Get
            Set
                OnBondedByChanging(value)
                ReportPropertyChanging("BondedBy")
                _BondedBy = StructuralObject.SetValidValue(value, false, "BondedBy")
                ReportPropertyChanged("BondedBy")
                OnBondedByChanged()
            End Set
        End Property
    
        Private _BondedBy As Global.System.String
        Private Partial Sub OnBondedByChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnBondedByChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property HowMuch() As Global.System.String
            Get
                Return _HowMuch
            End Get
            Set
                OnHowMuchChanging(value)
                ReportPropertyChanging("HowMuch")
                _HowMuch = StructuralObject.SetValidValue(value, false, "HowMuch")
                ReportPropertyChanged("HowMuch")
                OnHowMuchChanged()
            End Set
        End Property
    
        Private _HowMuch As Global.System.String
        Private Partial Sub OnHowMuchChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnHowMuchChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property ExpDate() As Global.System.String
            Get
                Return _ExpDate
            End Get
            Set
                OnExpDateChanging(value)
                ReportPropertyChanging("ExpDate")
                _ExpDate = StructuralObject.SetValidValue(value, false, "ExpDate")
                ReportPropertyChanged("ExpDate")
                OnExpDateChanged()
            End Set
        End Property
    
        Private _ExpDate As Global.System.String
        Private Partial Sub OnExpDateChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnExpDateChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
        <DataMemberAttribute()>
        Public Property FilerNo() As Global.System.String
            Get
                Return _FilerNo
            End Get
            Set
                OnFilerNoChanging(value)
                ReportPropertyChanging("FilerNo")
                _FilerNo = StructuralObject.SetValidValue(value, true, "FilerNo")
                ReportPropertyChanged("FilerNo")
                OnFilerNoChanged()
            End Set
        End Property
    
        Private _FilerNo As Global.System.String
        Private Partial Sub OnFilerNoChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnFilerNoChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
        <DataMemberAttribute()>
        Public Property FilerCode() As Global.System.String
            Get
                Return _FilerCode
            End Get
            Set
                OnFilerCodeChanging(value)
                ReportPropertyChanging("FilerCode")
                _FilerCode = StructuralObject.SetValidValue(value, true, "FilerCode")
                ReportPropertyChanged("FilerCode")
                OnFilerCodeChanged()
            End Set
        End Property
    
        Private _FilerCode As Global.System.String
        Private Partial Sub OnFilerCodeChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnFilerCodeChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
        <DataMemberAttribute()>
        Public Property irsnumber() As Global.System.String
            Get
                Return _irsnumber
            End Get
            Set
                OnirsnumberChanging(value)
                ReportPropertyChanging("irsnumber")
                _irsnumber = StructuralObject.SetValidValue(value, true, "irsnumber")
                ReportPropertyChanged("irsnumber")
                OnirsnumberChanged()
            End Set
        End Property
    
        Private _irsnumber As Global.System.String
        Private Partial Sub OnirsnumberChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnirsnumberChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
        <DataMemberAttribute()>
        Public Property Questionare() As Nullable(Of Global.System.Boolean)
            Get
                Return _Questionare
            End Get
            Set
                OnQuestionareChanging(value)
                ReportPropertyChanging("Questionare")
                _Questionare = StructuralObject.SetValidValue(value, "Questionare")
                ReportPropertyChanged("Questionare")
                OnQuestionareChanged()
            End Set
        End Property
    
        Private _Questionare As Nullable(Of Global.System.Boolean)
        Private Partial Sub OnQuestionareChanging(value As Nullable(Of Global.System.Boolean))
        End Sub
    
        Private Partial Sub OnQuestionareChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
        <DataMemberAttribute()>
        Public Property PermissionLetter() As Nullable(Of Global.System.Boolean)
            Get
                Return _PermissionLetter
            End Get
            Set
                OnPermissionLetterChanging(value)
                ReportPropertyChanging("PermissionLetter")
                _PermissionLetter = StructuralObject.SetValidValue(value, "PermissionLetter")
                ReportPropertyChanged("PermissionLetter")
                OnPermissionLetterChanged()
            End Set
        End Property
    
        Private _PermissionLetter As Nullable(Of Global.System.Boolean)
        Private Partial Sub OnPermissionLetterChanging(value As Nullable(Of Global.System.Boolean))
        End Sub
    
        Private Partial Sub OnPermissionLetterChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
        <DataMemberAttribute()>
        Public Property Agreement() As Nullable(Of Global.System.Boolean)
            Get
                Return _Agreement
            End Get
            Set
                OnAgreementChanging(value)
                ReportPropertyChanging("Agreement")
                _Agreement = StructuralObject.SetValidValue(value, "Agreement")
                ReportPropertyChanged("Agreement")
                OnAgreementChanged()
            End Set
        End Property
    
        Private _Agreement As Nullable(Of Global.System.Boolean)
        Private Partial Sub OnAgreementChanging(value As Nullable(Of Global.System.Boolean))
        End Sub
    
        Private Partial Sub OnAgreementChanged()
        End Sub

        #End Region

        #Region "Navigation Properties"
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <XmlIgnoreAttribute()>
        <SoapIgnoreAttribute()>
        <DataMemberAttribute()>
        <EdmRelationshipNavigationPropertyAttribute("DB_9AA143_mendyaModel", "Export_Company_FK", "Export")>
         Public Property Exports() As EntityCollection(Of Export)
            Get
                Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of Export)("DB_9AA143_mendyaModel.Export_Company_FK", "Export")
            End Get
            Set
                If (Not value Is Nothing)
                    CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of Export)("DB_9AA143_mendyaModel.Export_Company_FK", "Export", value)
                End If
            End Set
        End Property
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <XmlIgnoreAttribute()>
        <SoapIgnoreAttribute()>
        <DataMemberAttribute()>
        <EdmRelationshipNavigationPropertyAttribute("DB_9AA143_mendyaModel", "Import_Company_FK", "Import")>
         Public Property [Imports]() As EntityCollection(Of Import)
            Get
                Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of Import)("DB_9AA143_mendyaModel.Import_Company_FK", "Import")
            End Get
            Set
                If (Not value Is Nothing)
                    CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of Import)("DB_9AA143_mendyaModel.Import_Company_FK", "Import", value)
                End If
            End Set
        End Property

        #End Region

    End Class

    #End Region

End Namespace
