'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class edrawbackEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=edrawbackEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property Drawbacks() As DbSet(Of Drawback)
    Public Overridable Property Exports() As DbSet(Of Export)
    Public Overridable Property [Imports]() As DbSet(Of Import)
    Public Overridable Property Status() As DbSet(Of Status)
    Public Overridable Property Tarrifs() As DbSet(Of Tarrif)
    Public Overridable Property Users() As DbSet(Of User)
    Public Overridable Property database_firewall_rules() As DbSet(Of database_firewall_rules)

End Class
